from pathlib import Path
from argparse import ArgumentParser


class Block:
    def __init__(self) -> None:
        self.type: str = ""
        self.id: str = ""
        self.values: dict[str, str] = {}
        self.blocks: list[Block] = []


def parse_script(script: str) -> Block:
    block_stack: list[Block] = [Block()]

    last_pos: int = -1
    for i in range(len(script)):
        char = script[i]
        match char:
            case ",":
                value = script[last_pos + 1:i]
                equals_pos = value.find("=")
                key = value[:equals_pos - 1].strip()
                value = value[equals_pos + 1:].strip()
                block_stack[-1].values[key] = value
                last_pos = i
            case "{":
                strings = script[last_pos + 1:i - 1].strip().split(maxsplit=1)
                block = Block()
                block.type = strings[0]
                if len(strings) > 1:
                    block.id = strings[1]
                block_stack[-1].blocks.append(block)
                block_stack.append(block)
                last_pos = i
            case "}":
                assert len(block_stack) > 0
                block_stack.pop()
                last_pos = i

    assert len(block_stack) == 1
    return block_stack[0]


def write_script(block: Block) -> str:
    script = "/* This file is automatically generated. Changes may be lost. */\n\n"

    for block in block.blocks:
        script += write_block(block, 0)

    return script + "\n"


INDENT_STR = "    "


def write_block(block: Block, indent_level: int) -> str:
    newline = "\n" + INDENT_STR * (indent_level + 1)

    script: str = INDENT_STR * indent_level + block.type
    if block.id != "":
        script += f" {block.id}"
    script += " {"

    for key, value in block.values.items():
        script += newline + f"{key} = {value},"

    for i in range(len(block.blocks)):
        child = block.blocks[i]
        if i != 0:
            script += "\n"
        script += "\n" + write_block(child, indent_level + 1)

    script += "\n" + INDENT_STR * indent_level + "}"

    return script


def main() -> None:
    parser = ArgumentParser(
        prog="create_alt_models",
        description="Creates alternate models needed by Music for the End of the World"
    )
    parser.add_argument("file", type=Path)
    args = parser.parse_args()

    path: Path = args.file

    with path.open('r') as file:
        script = file.read()

    block = parse_script(script)
    assert block.blocks[0].type == "module"

    out_module = Block()
    out_module.type = "module"
    out_module.id = "MFTEOTW"

    for block in block.blocks[0].blocks:
        if block.type != "model":
            continue
        if block.values["mesh"] == "WorldItems/TCCover":
            flat_model = Block()
            flat_model.type = "model"
            flat_model.id = block.id + "_Flat"
            for k, v in block.values.items():
                flat_model.values[k] = v
            flat_model.values["mesh"] = "WorldItems/TCCover_1"

            attachment = Block()
            attachment.type = "attachment"
            attachment.id = "world"
            attachment.values = {
                "offset": "0 -0.02 0"
            }
            flat_model.blocks.append(attachment)

            out_module.blocks.append(flat_model)

    out_block = Block()
    out_block.blocks.append(out_module)
    with (path.parent / ("MTFEOTWModels_" + path.name)).open('w') as file:
        file.write(write_script(out_block))


if __name__ == "__main__":
    main()
