import json
import sys
import os

from pathlib import Path
from dataclasses import dataclass

from pyogg import PyOggError, VorbisFile


SCRIPT_HEADER: str = "/* Generated by TrackGen */\n\n"

ILLEGAL_CHARACTERS: set[str] = {" ", "-", ".", ","}


def sanitise(name: str) -> str:
    for char in ILLEGAL_CHARACTERS:
        name = name.replace(char, "")
    return name


def get_sound_duration(path: Path) -> float:
    try:
        file = VorbisFile(str(path.resolve()))
    except PyOggError as e:
        print(f"Unable to open file {path}")
        print(f"PyOgg Error: {e}")
        return 0
    # i don't know why dividing by two is needed, but it was accurate on all files tested
    return file.buffer_length / file.frequency / file.channels / 2


@dataclass
class Track:
    name: str
    sound: str
    display_name: str
    duration: float


def create_track(path: Path) -> Track:
    file_name = path.name.rsplit(".", 1)[0]
    return Track(
        name=sanitise(file_name),
        sound="Cassette" + sanitise(file_name),
        display_name=file_name,
        duration=get_sound_duration(path)
    )


def write_track_script(track: Track) -> str:
    """
    Deprecated pre-rewrite format.
    :param track:
    :return:
    """
    return (f"track {track.name} {{\n"
            f"    sound = {track.sound},\n"
            f"    duration = {track.duration},\n"
            f"}}\n"
            f"\n")


def write_script_file(tracks: list[Track]) -> str:
    """
    Deprecated pre-rewrite format.
    :param tracks:
    :return:
    """
    total_string = SCRIPT_HEADER

    for track in tracks:
        total_string += write_track_script(track)

    return total_string


def write_tracks(tracks: list[Track]) -> dict:
    track_map = {}
    for track in tracks:
        track_map[track.name] = {
            "sound": track.sound,
            "duration": track.duration
        }

    return track_map


def write_track_group(tracks: list[Track]) -> list:
    return list({"track": track.name, "weight": 1} for track in tracks)


def write_json(path: Path, tracks: list[Track]) -> None:
    with path.open('w', encoding="utf-8") as file:
        json.dump(
            {
                "tracks": write_tracks(tracks),
                "trackGroups": {
                    "TrackGen_Tracks": write_track_group(tracks)
                }
            },
            file,
            indent=4
        )


def write_translations_file(tracks: list[Track]) -> str:
    total_string = ""

    for track in tracks:
        total_string += f"track_{track.name} = \"{track.display_name}\",\n"

    return total_string


def create_tracks(paths: list[Path]) -> list[Track]:
    """
    Creates script blocks for all the files in filenames.
    :param paths: List of filepaths to sound files.
    :return:
    """
    files: list[Path] = []
    for path in paths:
        if not path.exists():
            print(f"{path} does not exist, skipping.")
            continue

        if path.is_file():
            files.append(path)
        else:
            for _, _, filenames in os.walk(path):
                for file in filenames:
                    if file.endswith(".ogg"):
                        files.append(path / file)

    tracks: list[Track] = []
    for path in files:
        tracks.append(create_track(path))

    return tracks


def main() -> None:
    paths = []
    for path in sys.argv[1:]:
        paths.append(Path(path))

    tracks = create_tracks(paths)

    write_json(Path("TrackGen_tracks.json"), tracks)

    with Path("TrackGen_en.txt").open("w", encoding="utf-8") as file:
        file.write(write_translations_file(tracks))

    with Path("TrackGen_list.txt").open("w", encoding="utf-8") as file:
        for track in tracks:
            file.write(track.name + ",\n")


if __name__ == '__main__':
    main()
