import sys, os
from pathlib import Path

from pyogg import PyOggError, VorbisFile


SCRIPT_HEADER: str = "/* Generated by TrackGen */\n\n"

ILLEGAL_CHARACTERS: set[str] = {" ", "-", ".", ","}


def generate_track(name: str, sound: str, duration: float) -> str:
    """
    Creates a script block with the passed data, and adds it to self.trackScript
    :param name: Name of the track
    :param sound: The sound script the track relates to
    :param duration: The duration of the sound in seconds
    :return:
    """
    return f"track {name} {{\n    sound = {sound},\n    duration = {duration},\n}}\n\n"


def generate_tracks(paths: list[Path]) -> str:
    """
    Creates script blocks for all the files in filenames.
    :param paths: List of filepaths to sound files.
    :return:
    """
    if len(paths) < 1:
        print("No files were provided")
        return ""

    files: list[Path] = []
    for path in paths:
        if not path.exists():
            print(f"{path} does not exist, skipping.")
            continue

        if path.is_file():
            files.append(path)
        else:
            for _, _, filenames in os.walk(path):
                for file in filenames:
                    if file.endswith(".ogg"):
                        files.append(path / file)

    num_files: int = len(files)
    if num_files < 1:
        print("No files were found")
        return ""

    total_str = ""

    skipped_files: int = 0
    for path in files:
        try:
            file = VorbisFile(str(path.resolve()))
        except PyOggError as e:
            print(f"Unable to open file {path}, skipping")
            print(f"PyOgg Error: {e}")
            skipped_files += 1
            continue
        # i don't know why dividing by two is needed, but it was accurate on all files tested
        duration = file.buffer_length / file.frequency / file.channels / 2

        track_name: str = path.name.rsplit(".", 1)[0]
        for char in ILLEGAL_CHARACTERS:
            track_name = track_name.replace(char, "")
        # TODO: can we generate a translations file from the metadata?
        # TODO: switch to disable the truemusicification
        total_str += generate_track(track_name, f"Cassette{track_name}", duration)

    if skipped_files > 0:
        print(f"Skipped {skipped_files} of {num_files} files")

    return total_str


def main() -> None:
    paths = []
    for path in sys.argv[1:]:
        paths.append(Path(path))

    total_string = generate_tracks(paths)
    total_string = SCRIPT_HEADER + total_string

    # TODO: switch to change output name
    with Path("TrackGen_tracks.txt").open("w", encoding="utf-8") as file:
        file.write(total_string)
        file.close()


if __name__ == '__main__':
    main()
